### ISSUE TITLE
not able to extract the file 

### ISSUE THREAD

**Issue by Digiguy1** [tofke/XBI-MN-setup#1]
tar zxvf xbi-ubuntu-16.04-aarch64.tar.gz 

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by tofke** [comment]
I have been told about this issue by a member of Discord channel, and changed the download line to go get the file in "release" folder instead of the main page (downloading from the main page only works if you are in a browser, as it redirects you to the binary file). 

You probably did not use the correct "wget ..." command as it is written in the README.md ? 
(maybe you copied the link to the files in the main directory?)
The problem is that this links downloads an html file instead of the tar.gz compressed archive (see it with the command "file xbi-*.tar.gz").

Use the appropriate URL (with ".../releases/download/..." in it) and it should work.

I'm working on an update script to simplify the setup process.
